import { addIcon } from '@iconify/svelte';

import lightbulb from '@iconify-icons/mdi/lightbulb';
import checkBold from '@iconify-icons/mdi/check-bold';
import dumbbell from '@iconify-icons/mdi/dumbbell';
import shapeOutline from '@iconify-icons/mdi/shape-outline';
import vectorLink from '@iconify-icons/mdi/vector-link';
import lockOutline from '@iconify-icons/mdi/lock-outline';
import feather from '@iconify-icons/mdi/feather';
import atom from '@iconify-icons/mdi/atom';
import github from '@iconify-icons/mdi/github';
import bookOpenVariant from '@iconify-icons/mdi/book-open-variant';
import logout from '@iconify-icons/mdi/logout';
import homeOutline from '@iconify-icons/mdi/home-outline';
import login from '@iconify-icons/mdi/login';
import viewDashboardOutline from '@iconify-icons/mdi/view-dashboard-outline';
import contentSaveOutline from '@iconify-icons/mdi/content-save-outline';
import menu from '@iconify-icons/mdi/menu';
import menuOpen from '@iconify-icons/mdi/menu-open';
import lightbulbOnOutline from '@iconify-icons/mdi/lightbulb-on-outline';
import accountQuestionOutline from '@iconify-icons/mdi/account-question-outline';
import history from '@iconify-icons/mdi/history';
import eyeOutline from '@iconify-icons/mdi/eye-outline';
import refresh from '@iconify-icons/mdi/refresh';
import meditation from '@iconify-icons/mdi/meditation';
import paperclip from '@iconify-icons/mdi/paperclip';
import cellphone from '@iconify-icons/mdi/cellphone';
import cellphoneOff from '@iconify-icons/mdi/cellphone-off';
import cameraOutline from '@iconify-icons/mdi/camera-outline';
import formatQuoteClose from '@iconify-icons/mdi/format-quote-close';
import fence from '@iconify-icons/mdi/fence';
import pencilRuler from '@iconify-icons/mdi/pencil-ruler';
import walk from '@iconify-icons/mdi/walk';
import timerOutline from '@iconify-icons/mdi/timer-outline';
import swapHorizontal from '@iconify-icons/mdi/swap-horizontal';
import merge from '@iconify-icons/mdi/merge';
import volumeOff from '@iconify-icons/mdi/volume-off';
import handHeart from '@iconify-icons/mdi/hand-heart';
import accountStarOutline from '@iconify-icons/mdi/account-star-outline';
import imageText from '@iconify-icons/mdi/image-text';
import mapMarkerPath from '@iconify-icons/mdi/map-marker-path';
import hourglassEmpty from '@iconify-icons/mdi/hourglass-empty';
import hammerWrench from '@iconify-icons/mdi/hammer-wrench';
import checkDecagramOutline from '@iconify-icons/mdi/check-decagram-outline';
import formatQuoteCloseOutline from '@iconify-icons/mdi/format-quote-close-outline';
import shareVariant from '@iconify-icons/mdi/share-variant';
import emailOutline from '@iconify-icons/mdi/email-outline';
import flagCheckered from '@iconify-icons/mdi/flag-checkered';

addIcon('mdi:lightbulb', lightbulb);
addIcon('mdi:check-bold', checkBold);
addIcon('mdi:dumbbell', dumbbell);
addIcon('mdi:shape-outline', shapeOutline);
addIcon('mdi:vector-link', vectorLink);
addIcon('mdi:lock-outline', lockOutline);
addIcon('mdi:feather', feather);
addIcon('mdi:atom', atom);
addIcon('mdi:github', github);
addIcon('mdi:book-open-variant', bookOpenVariant);
addIcon('mdi:logout', logout);
addIcon('mdi:home-outline', homeOutline);
addIcon('mdi:login', login);
addIcon('mdi:view-dashboard-outline', viewDashboardOutline);
addIcon('mdi:content-save-outline', contentSaveOutline);
addIcon('mdi:menu', menu);
addIcon('mdi:menu-open', menuOpen);
addIcon('mdi:lightbulb-on-outline', lightbulbOnOutline);
addIcon('mdi:account-question-outline', accountQuestionOutline);
addIcon('mdi:history', history);
addIcon('mdi:eye-outline', eyeOutline);
addIcon('mdi:refresh', refresh);
addIcon('mdi:meditation', meditation);
addIcon('mdi:paperclip', paperclip);
addIcon('mdi:cellphone', cellphone);
addIcon('mdi:cellphone-off', cellphoneOff);
addIcon('mdi:camera-outline', cameraOutline);
addIcon('mdi:format-quote-close', formatQuoteClose);
addIcon('mdi:fence', fence);
addIcon('mdi:pencil-ruler', pencilRuler);
addIcon('mdi:walk', walk);
addIcon('mdi:timer-outline', timerOutline);
addIcon('mdi:swap-horizontal', swapHorizontal);
addIcon('mdi:merge', merge);
addIcon('mdi:volume-off', volumeOff);
addIcon('mdi:hand-heart', handHeart);
addIcon('mdi:account-star-outline', accountStarOutline);
addIcon('mdi:image-text', imageText);
addIcon('mdi:map-marker-path', mapMarkerPath);
addIcon('mdi:hourglass-empty', hourglassEmpty);
addIcon('mdi:hammer-wrench', hammerWrench);
addIcon('mdi:check-decagram-outline', checkDecagramOutline);
addIcon('mdi:format-quote-close-outline', formatQuoteCloseOutline);
addIcon('mdi:share-variant', shareVariant);
addIcon('mdi:email-outline', emailOutline);
addIcon('mdi:flag-checkered', flagCheckered);
