services:
  app:
    build: .
    container_name: toughskill-app
    restart: unless-stopped
    user: '1001:1001'
    env_file: .env
    volumes:
      - ./data:/data
    networks:
      - default
      - web

networks:
  web:
    external: true
